name: Push

on:
  push:
    branches: [ master, AddTest ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: 버전 추가
      env:
        TAG_NAME: ${{ github.ref }}
      run: |
        get-childitem ./ -recurse -include *.csproj | ForEach-Object {(get-content -encoding utf8 $_.FullName) -replace '0.0.0.0', '0.0.0' | out-file -encoding utf8 $_.FullName}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ToastNotifier
        # Directory containing files to upload
        path: bin\Release\net472
